---

- name: Install Openlogic-openjdk-jre from the files directory
  block:

    - name: "Copy openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz to directory {{ log4j_detector_on_java_dir_work }}"
      copy:
        src: "openjdk/openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz"
        dest: "{{ log4j_detector_on_java_dir_work }}/openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz"
        mode: 0640

    - name: "Get sha256sum of openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz"
      stat:
        path: "{{  log4j_detector_on_java_dir_work }}/openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz"
        checksum_algorithm: sha256
        get_checksum: yes
      register: stat_result

    - name: "Verify sha256sum of openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz before extraction"
      fail:
        msg: "sha256sum mismatch for file openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz"
      when: stat_result.stat.checksum != log4j_detector_on_java_openjdk.checksum

    - name: "Extract openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz to {{ log4j_detector_on_java_dir_openjdk }} directory"
      unarchive:
        src: "{{ log4j_detector_on_java_dir_work }}/openlogic-openjdk-jre-{{ log4j_detector_on_java_openjdk.version }}-linux-x64.tar.gz"
        dest: "{{ log4j_detector_on_java_dir_openjdk }}"
        extra_opts: [--strip-components=1]
        remote_src: yes
